exec-once = alacritty
exec-once = swayidle -w timeout 300 'wlopm --off *' resume 'wlopm --on *' timeout 600 'loginctl suspend'
exec-once = gentoo-pipewire-launcher &
exec-once = swaybg -i ~/Downloads/wallhaven-zpqp6g.jpg -m fill
exec-once = waybar

monitorrule = name:HDMI-A-1, width: 1920, height: 1080, refresh: 100

allow_tearing = 2
focus_on_activate = 0
sloppyfocus = 0

repeat_rate = 35
repeat_delay = 250
xkb_rules_layout = us,ru,ua
xkb_rules_options = grp:caps_toggle

borderpx = 2
bordercolor = 0x1f1f1fff
focuscolor = 0x81a1c1ff
gappih = 5
gappiv = 5
gappoh = 15
gappov = 15

bind = SUPER, Return, spawn, alacritty
bind = SUPER, code:57, spawn, firefox-bin
bind = SUPER, code:40, spawn, vesktop-bin
bind = SUPER, code:25, spawn, steam
bind = SUPER, code:45, spawn, spotify
bind = SUPER, code:38, spawn, telegram-desktop
bind = SUPER, code:26, spawn, nemo
bind = SUPER, code:24, spawn, fuzzel
bind = SUPER, code:32, spawn, grim - | wl-copy
bind = SUPER, code:33, spawn, grim -g "$(slurp)" - | wl-copy

bind = SUPER, code:54, killclient
bind = SUPER, code:41, togglefullscreen
bind = SUPER, code:55, togglefloating

bind = SUPER, Left, focusdir, left
bind = SUPER, Right, focusdir, right
bind = SUPER, Up, focusdir, up
bind = SUPER, Down, focusdir, down

bind = SUPER+SHIFT, Up, exchange_client, up
bind = SUPER+SHIFT, Down, exchange_client, down
bind = SUPER+SHIFT, Left, exchange_client, left
bind = SUPER+SHIFT, Right, exchange_client, right

bind = SUPER, 1, view, 1
bind = SUPER, 2, view, 2
bind = SUPER, 3, view, 3
bind = SUPER, 4, view, 4
bind = SUPER, 5, view, 5
bind = SUPER, 6, view, 6
bind = SUPER, 7, view, 7
bind = SUPER, 8, view, 8
bind = SUPER, 9, view, 9

bind = SUPER+SHIFT, 1, tag, 1
bind = SUPER+SHIFT, 2, tag, 2
bind = SUPER+SHIFT, 3, tag, 3
bind = SUPER+SHIFT, 4, tag, 4
bind = SUPER+SHIFT, 5, tag, 5
bind = SUPER+SHIFT, 6, tag, 6
bind = SUPER+SHIFT, 7, tag, 7
bind = SUPER+SHIFT, 8, tag, 8
bind = SUPER+SHIFT, 9, tag, 9

bind = SUPER+SHIFT, code:45, resizewin, +0, -50
bind = SUPER+SHIFT, code:44, resizewin, +0, +50
bind = SUPER+SHIFT, code:43, resizewin, -50, +0
bind = SUPER+SHIFT, code:46, resizewin, +50, +0

mousebind = SUPER, btn_left, moveresize, curmove
mousebind = SUPER, btn_right, moveresize, curresize

bind = NONE, XF86AudioRaiseVolume, spawn, wpctl set-volume @DEFAULT_SINK@ 5%+
bind = NONE, XF86AudioLowerVolume, spawn, wpctl set-volume @DEFAULT_SINK@ 5%-
bind = NONE, XF86AudioMute, spawn, wpctl set-mute @DEFAULT_SINK@ toggle

bind = SUPER+SHIFT, code:58, quit
